micro.web.routing.hello.methods=GET,POST
micro.web.routing.hello.path=/hello
micro.web.routing.hello.regex=/hello
micro.web.routing.hello-name.path=/hello/path/:name
micro.web.routing.hello-name-re.regex=\/hello\/re\/([a-zA-Z]+)
micro.web.routing.hello-name-re-group.regex=\/hello\/regr\/(?<name>[a-zA-Z]+)
